name: HolyHocotts
favicon: null
layout_spectrum: 1
typography_spectrum: 0.85594
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#19bcb9'
    - '#ee2e24'
    - '#8cdddc'
    - '#767d77'
  brandStrength: 0.5625
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.2134848
purpose: []
