analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5
  brandStrength: 0.5191489
  lightness: 0.6875
  brandColors:
    - '#0E0B02'
    - '#888689'
    - '#656530'
    - '#DFAD2F'
    - '#772802'
  rhythmicContrast: 1
typography_spectrum: 0.85594
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
favicon: null
name: HolyHocotts
